// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ4SzcyFZrPScq6Zb-mbBgI2BBp-cpUO8',
    appId: '1:489634597257:web:6df4635f72c9f8ef7db958',
    messagingSenderId: '489634597257',
    projectId: 'carebuddy-3649e',
    authDomain: 'carebuddy-3649e.firebaseapp.com',
    databaseURL: 'https://carebuddy-3649e-default-rtdb.firebaseio.com',
    storageBucket: 'carebuddy-3649e.firebasestorage.app',
    measurementId: 'G-H1G4RNCX8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXr_jdzYZZNv-46lo8v6gQh5_tazY1Bhg',
    appId: '1:489634597257:android:01bcec3a2a7980257db958',
    messagingSenderId: '489634597257',
    projectId: 'carebuddy-3649e',
    databaseURL: 'https://carebuddy-3649e-default-rtdb.firebaseio.com',
    storageBucket: 'carebuddy-3649e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABK2e7U59OH9-I-L35XPIU0NXF_NsXWXg',
    appId: '1:489634597257:ios:a2168bae6b87e3ca7db958',
    messagingSenderId: '489634597257',
    projectId: 'carebuddy-3649e',
    databaseURL: 'https://carebuddy-3649e-default-rtdb.firebaseio.com',
    storageBucket: 'carebuddy-3649e.firebasestorage.app',
    iosBundleId: 'com.example.carebuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABK2e7U59OH9-I-L35XPIU0NXF_NsXWXg',
    appId: '1:489634597257:ios:a2168bae6b87e3ca7db958',
    messagingSenderId: '489634597257',
    projectId: 'carebuddy-3649e',
    databaseURL: 'https://carebuddy-3649e-default-rtdb.firebaseio.com',
    storageBucket: 'carebuddy-3649e.firebasestorage.app',
    iosBundleId: 'com.example.carebuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ4SzcyFZrPScq6Zb-mbBgI2BBp-cpUO8',
    appId: '1:489634597257:web:5fecd4605af647737db958',
    messagingSenderId: '489634597257',
    projectId: 'carebuddy-3649e',
    authDomain: 'carebuddy-3649e.firebaseapp.com',
    databaseURL: 'https://carebuddy-3649e-default-rtdb.firebaseio.com',
    storageBucket: 'carebuddy-3649e.firebasestorage.app',
    measurementId: 'G-0W0S6EYC4F',
  );
}
